development:
  adapter: postgresql
  encoding: utf8
  database: comb_development
  pool: 5
  timeout: 5000
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: comb_test
  pool: 5
  timeout: 5000
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: comb_production
  pool: 5
  timeout: 5000
  username:
  password:
